#' Plot correlation between outcome and diversity, versus projection period, coloured by K, for each value of tumour size at measurement
#' 
#' @param df dataframe generated by get_cor_summary
#' @param output_dir folder in which to save the image file; if NA then plots are displayed on screen instead
#' @param output_filename name of output image file
#' @param file_type either "pdf" or "png" (other values default to "pdf")
#' 
#' @return a plot object
#' 
#' @export
#' @import dplyr
#' @importFrom graphics abline
#' @importFrom graphics legend
#' 
#' @examples 
#' plot_corr_outcome_versus_period(cor_summary)
plot_corr_outcome_versus_period <- function(df, output_filename = NA, file_type = "png", output_dir = NA) {
  if(!is.na(output_filename)) if(substr(output_dir, nchar(output_dir), nchar(output_dir)) != "/") output_dir <- paste0(output_dir, "/")
  
  if(!is.na(output_dir)) {
    if(file_type == "png") png(paste0(output_dir, output_filename,".png"), width = 1000, height = 1000, res = 100)
    else pdf(paste0(output_dir, output_filename,".pdf"), width = 500, height = 600)
  }
  
  start_size_range <- unique(df$start_size)
  K_range <- unique(df$K)
  
  cols <- rainbow(8)
  cols[5] <- "blue"
  
  par(mfrow=c(2, 3))
  par(mar=c(4.5, 4, 1.5, 1))
  for(start_size_val in start_size_range) {
    title <- paste("Measure at ", start_size_val, " cells", sep = "")
    for(K_val in K_range) {
      if(K_val == K_range[1]) {
        plot(1, type = "n", xlim = c(0, 1), ylim = c(-0.1, 1),
             main = title, xlab = "projection period", ylab = "correlation coefficient: diversity vs tumour size")
        if(start_size_val == start_size_range[1]) legend("topright", as.character(K_range), title = "K", 
                                                     xpd = TRUE, horiz = FALSE, inset = c(0.1, 0.03), bty = "n", lty = 1, col = cols)
      }
      lines(Cor_DriverDiversity ~ gap, data = filter(df, start_size == start_size_val, K == K_val), 
            col = cols[log2(K) + 1], lwd = 2)
      abline(h = 0, untf = FALSE, lty = 3)
    }
  }
  
  if(!is.na(output_dir)) dev.off()
}

#' Plot correlation between waiting time and diversity, versus tumour size at measurement, coloured by K
#' 
#' @param df dataframe generated by get_wait_cor_summary
#' @param output_dir folder in which to save the image file; if NA then plots are displayed on screen instead
#' @param output_filename name of output image file
#' @param file_type either "pdf" or "png" (other values default to "pdf")
#' 
#' @return a plot object
#' 
#' @export
#' @import dplyr
#' @importFrom grDevices rainbow
#' @importFrom graphics legend
#' 
#' @examples 
#' plot_corr_waiting_time_versus_start_size(wait_cor_summary)
plot_corr_waiting_time_versus_start_size <- function(df, output_filename = NA, file_type = "png", output_dir = NA) {
  if(!is.na(output_filename)) if(substr(output_dir, nchar(output_dir), nchar(output_dir)) != "/") output_dir <- paste0(output_dir, "/")
  
  if(!is.na(output_dir)) {
    if(file_type == "png") png(paste0(output_dir, output_filename, ".png"), width = 1000, height = 1000, res = 100)
    else pdf(paste0(output_dir, output_filename, ".pdf"), width = 500, height = 600)
    }
  
  start_size_range <- unique(df$start_size)
  K_range <- unique(df$K)
  
  cols <- rainbow(8)
  cols[5] <- "blue"
  
  par(mfrow=c(1, 1))
  par(mar=c(4, 4, 2, 2))
  for(K_val in K_range) {
    if(K_val == K_range[1]) {
      plot(1, type = "n", xlim = c(0, 6E3), ylim = c(-1, 1),
           main = "", xlab = "tumour size at measurement", ylab = "correlation coefficient: diversity vs waiting time")
      legend("topright", as.character(K_range), title = "K", 
             xpd = TRUE, horiz = FALSE, inset = c(0.1, 0.03), bty = "n", lty = 1, col = cols)
      }
      lines(Cor_DriverDiversity ~ start_size, data = filter(df, K == K_val), 
            col = cols[log2(K) + 1], lwd = 2)
      abline(h = 0, untf = FALSE, lty = 3)
      }
  
  if(!is.na(output_dir)) dev.off()
}

#' Plot correlations between waiting time and diversity measured at different depths, coloured by size at measurement
#' 
#' @param df dataframe generated by get_wait_cor_summary
#' @param col_prefix text that appears in all names of columns containing correlation statistics
#' @param output_dir folder in which to save the image file; if NA then plots are displayed on screen instead
#' @param output_filename name of output image file
#' @param file_type either "pdf" or "png" (other values default to "pdf")
#' 
#' @return a plot object
#' 
#' @export
#' 
#' @examples
#' library(dplyr)
#' plot_corr_waiting_time_versus_depth(filter(depth_wait_cor_summary, K == 16), 
#' "DriverDiversityFrom1SamplesAtDepth")
plot_corr_waiting_time_versus_depth <- function(df, col_prefix, output_filename = NA, file_type = "png", output_dir = NA) {
  
  par(mfrow=c(1,1))
  par(mar=c(4.5,5,1,1))
  col_nums <- which(grepl(col_prefix, colnames(df)))
  depth <- (0:(length(col_nums)-1)) / (length(col_nums)-1)
  sizes <- unique(df$start_size)
  cols <- rainbow(length(sizes))
  par(oma = c(0, 0, 0, 3))
  plot(as.numeric(df[which(df$start_size == sizes[1]), col_nums]) ~ depth, ylim = c(-1, 0), col = cols[1], type = "l",
       xlab = "measurement distance from periphery (%)", 
       ylab = "correlation coefficient: diversity vs waiting time", xaxt = "n", lwd = 2)
  axis(1, at=2*0:5,labels=20*0:5)
  for(i in 2:length(sizes)) {
    lines(as.numeric(df[which(df$start_size == sizes[i]), col_nums]) ~ depth, col = cols[i], lwd = 2)
  }
  par(fig = c(0, 1, 0, 1), oma = c(0, 0, 0, 0), mar = c(0, 0, 0, 0), new = TRUE)
  plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n")
  legend("bottomright", as.character(sizes), title = "size at measurement", xpd = TRUE, 
         horiz = FALSE, inset = c(0.2, 0.3), bty = "n", lty = 1, col = cols, lwd = 2)
}

#' Plot growth trajectories, coloured by K
#' 
#' @param df data frame
#' @param output_dir folder in which to save the image file; if NA then plots are displayed on screen instead
#' @param output_filename name of output image file
#' @param file_type either "pdf" or "png" (other values default to "pdf")
#' 
#' @return a plot object
#' 
#' @export
#' @import ggplot2
#' 
#' @examples 
#' plot_trajectories_by_K(data)
plot_trajectories_by_K <- function(df, output_filename = NA, file_type = "png", output_dir = NA) {
  if(!is.na(output_filename)) if(substr(output_dir, nchar(output_dir), nchar(output_dir)) != "/") output_dir <- paste0(output_dir, "/")
  
  if(!is.na(output_dir)) {
    if(file_type == "png") png(paste0(output_dir, output_filename, ".png"), width = 1000, height = 1000, res = 100)
    else pdf(paste0(output_dir, output_filename, ".pdf"), width = 500, height = 600)
  }
  
  q <- qplot(
    gen_adj,
    NumCells,
    group = interaction(K, seed),
    data = df,
    colour = factor(K),
    geom = "line")
  print(q)
  
  if(!is.na(output_dir)) dev.off()
}

#' Plot growth trajectories, coloured by driver edge diversity
#' 
#' @param df data frame
#' @param output_dir folder in which to save the image file; if NA then plots are displayed on screen instead
#' @param output_filename name of output image file
#' @param file_type either "pdf" or "png" (other values default to "pdf")
#' 
#' @return a plot object
#' 
#' @export
#' @import ggplot2
#' @import RColorBrewer
#' 
#' @examples 
#' plot_trajectories_by_diversity(data)
plot_trajectories_by_diversity <- function(df, output_filename = NA, file_type = "png", output_dir = NA) {
  if(!is.na(output_filename)) if(substr(output_dir, nchar(output_dir), nchar(output_dir)) != "/") output_dir <- paste0(output_dir, "/")
  
  if(!is.na(output_dir)) {
    if(file_type == "png") png(paste0(output_dir, output_filename, ".png"), width = 1000, height = 1000, res = 100)
    else pdf(paste0(output_dir, output_filename, ".pdf"), width = 500, height = 600)
  }
  
  qp2 <- qplot(
    new_time,
    NumCells,
    group = interaction(seed, K),
    data = df,
    colour = div0,
    geom = "line")
  qp2 <- qp2 + scale_colour_gradientn(colours = c(brewer.pal(5, "RdYlBu"), "#0000FF"), name = "diversity at periphery") +
    facet_grid(.~K, scales = "free") +
    scale_x_continuous(name = "relative time") +
    scale_y_continuous(name = "tumour size") +
    theme_classic()
  print(qp2)
  
  if(!is.na(output_dir)) dev.off()
}

# example correlations of outcome/waiting time with edge diversity (JohnCode1)


# sweep metric against time (JohnCode2)


# violin plot of mean/skew autocorrelation (JohnCode2)


# growth trajectory coloured by mean sweep index for that simulation (JohnCode3; PlotCodeForJohn)


# R-squared by mean theta (JohnCode3)


# Mean rates (histograms_rates)






